"""
Django settings for slick_demo project.

Generated by 'django-admin startproject' using Django 3.0.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$y6(((t+0t*o9(ps9-7mvu=v%zt15u^5l_qrjq$_b2fz_&hfrj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['django-slick-reporting.com', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'slick_example.apps.SlickExampleConfig',
    'slick_reporting',
    'crispy_forms',
    # 'slick_example',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'slick_demo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'slick_example.context_processor.menu'
            ],
        },
    },
]

WSGI_APPLICATION = 'slick_demo.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'collected_static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

ADMINS = (('Ramez', 'ramezashraf@gmail.com'),)

CRISPY_TEMPLATE_PACK = 'bootstrap4'

from django.utils.translation import gettext_lazy as _

MENU = (
    ('', _('Welcome')),
    ('setup', _('Report Model')),
    ('no-group-by', _('Simple Filter')),
    ('no-group-by-plus-charts', _('Simple Filter tidying up')),

    ('group-by', _('Group By')),
    ('group-by-chart', _('Charting 101')),
    ('group-by-with-several-charts', _('Group By report with several charts')),
    ('group-by-date', _('Group By a date field')),

    ('time-series', _('Time Series')),
    ('time-series-charts', _('Time Series Customization')),
    ('time-series-without-group-by', _('Time series (without Group by)')),

    ('crosstab', _('Crosstab')),
    ('crosstab-charts', _('Crosstab Customization')),

    # ('crosstab-charts', _('Integration in your own views')),
    # ('crosstab-charts', _('Writing your own chart')),

    # ('crosstab-charts', _('Form Customization')),
    # ('crosstab-charts', _('ReportFields')),
    ('thank-you', _('End Walk through')),

)
