# Generated by Django 3.0.9 on 2020-08-06 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='For fast recall', unique=True, verbose_name='Identifier slug')),
                ('title', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='For fast recall', unique=True, verbose_name='Identifier slug')),
                ('title', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='For fast recall', unique=True, verbose_name='Identifier slug')),
                ('title', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, verbose_name='refer code')),
                ('doc_date', models.DateTimeField(db_index=True, verbose_name='date')),
                ('doc_type', models.CharField(db_index=True, max_length=30)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='value')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slick_example.Client')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='SalesLineTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, verbose_name='refer code')),
                ('doc_date', models.DateTimeField(db_index=True, verbose_name='date')),
                ('doc_type', models.CharField(db_index=True, max_length=30)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='value')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='price')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slick_example.Client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slick_example.Product')),
                ('sales_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slick_example.SalesTransaction')),
            ],
            options={
                'verbose_name': 'Sale Transaction Item',
                'verbose_name_plural': 'Sale Transaction Items',
            },
        ),
        migrations.CreateModel(
            name='ExpenseTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, verbose_name='refer code')),
                ('doc_date', models.DateTimeField(db_index=True, verbose_name='date')),
                ('doc_type', models.CharField(db_index=True, max_length=30)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='value')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slick_example.Expense')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
    ]
