# Generated by Django 3.0.9 on 2020-12-05 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slick_example', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
