# Generated by Django 3.0.9 on 2020-12-05 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slick_example', '0002_auto_20201205_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensetransaction',
            old_name='doc_date',
            new_name='transaction_date',
        ),
        migrations.RenameField(
            model_name='saleslinetransaction',
            old_name='doc_date',
            new_name='transaction_date',
        ),
        migrations.RenameField(
            model_name='salestransaction',
            old_name='doc_date',
            new_name='transaction_date',
        ),
    ]
